import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import "@/assets/style/App.scss";
import { Navbar } from "@/components/NavBar";
import { Footer } from "@/components/Footer";

const font = Work_Sans({ subsets: ["latin"], weight: ["300", "400", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={font.className}
        suppressHydrationWarning={true}
      >
        <div className="text-white flex flex-col h-screen">
          <Navbar />

          <div className="flex-auto">
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
